"""Add details_id to source table

Revision ID: 344950a73d7c
Revises: fbd5881d8893
Create Date: 2025-10-19 22:19:57.022893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344950a73d7c'
down_revision: Union[str, Sequence[str], None] = 'fbd5881d8893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_tags',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_id', 'tag_id')
    )
    op.add_column('sources', sa.Column('details_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'details_id')
    op.drop_table('quote_tags')
    # ### end Alembic commands ###
