"""Link quotes to sources

Revision ID: c26936a2e9ad
Revises: 5cd38c6c7b48
Create Date: 2025-10-14 19:20:57.579929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c26936a2e9ad'
down_revision: Union[str, Sequence[str], None] = '5cd38c6c7b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('book', 'movie', 'tv', 'speech', 'other', name='source_type'), nullable=False),
    sa.Column('creator', sa.String(length=255), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('producer_id', sa.Integer(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('source')
    op.add_column('quotes', sa.Column('source_id', sa.Integer(), nullable=False))
    op.alter_column('quotes', 'page',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'quotes', 'sources', ['source_id'], ['id'])
    op.create_foreign_key(None, 'quotes', 'users', ['user_id'], ['id'])
    op.drop_column('quotes', 'book_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.alter_column('quotes', 'page',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('quotes', 'source_id')
    op.create_table('source',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('source_type', mysql.ENUM('book', 'movie', 'tv', 'speech', 'other'), nullable=False),
    sa.Column('creator', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('pd_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', mysql.JSON(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['pd_id'], ['producers.id'], name=op.f('source_ibfk_1'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('sources')
    # ### end Alembic commands ###
