"""Add bookmark folders and standardize source models

Revision ID: fbd5881d8893
Revises: e6a1b2c3d4f5
Create Date: 2025-10-19 21:40:59.240667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fbd5881d8893'
down_revision: Union[str, Sequence[str], None] = 'e6a1b2c3d4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmark_folders_id'), 'bookmark_folders', ['id'], unique=False)
    op.create_table('dramas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('producer_id', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dramas_id'), 'dramas', ['id'], unique=False)
    op.create_index(op.f('ix_dramas_title'), 'dramas', ['title'], unique=False)
    op.drop_table('quote_tags')
    op.add_column('bookmarks', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookmarks', 'bookmark_folders', ['folder_id'], ['id'])
    op.drop_constraint(op.f('quotes_ibfk_3'), 'quotes', type_='foreignkey')
    op.drop_column('quotes', 'movie_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('movie_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('quotes_ibfk_3'), 'quotes', 'movies', ['movie_id'], ['id'])
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.drop_column('bookmarks', 'folder_id')
    op.create_table('quote_tags',
    sa.Column('quote_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('quote_tags_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('quote_tags_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_id', 'tag_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_dramas_title'), table_name='dramas')
    op.drop_index(op.f('ix_dramas_id'), table_name='dramas')
    op.drop_table('dramas')
    op.drop_index(op.f('ix_bookmark_folders_id'), table_name='bookmark_folders')
    op.drop_table('bookmark_folders')
    # ### end Alembic commands ###
